# Generated by Django 2.1.5 on 2019-01-30 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('published', models.BooleanField(default=True, verbose_name='Publicado?')),
                ('featured', models.BooleanField(default=True, verbose_name='Em destaque na página inicial?')),
                ('title', models.CharField(help_text='Título', max_length=255, verbose_name='Título')),
                ('teaser', models.TextField(blank=True, help_text='Resumo ou chamada', null=True, verbose_name='Resumo ou chamada')),
                ('url', models.CharField(db_index=True, max_length=100, verbose_name='Endereço')),
                ('body', models.TextField(verbose_name='Corpo da página')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staticpage_creator', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staticpage_last_modifier', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
