# Generated by Django 2.1.5 on 2019-01-30 13:54

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticpage',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(default='', upload_to='', verbose_name='Imagem'),
            preserve_default=False,
        ),
    ]
