# Generated by Django 2.1.5 on 2019-01-30 13:55

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_staticpage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticpage',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='', verbose_name='Imagem'),
        ),
    ]
