# Generated by Django 2.1.5 on 2019-02-01 14:34

from django.db import migrations, models
import xram_memory.quill_widget


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_auto_20190130_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticpage',
            name='body',
            field=models.TextField(validators=[xram_memory.quill_widget.no_empty_html], verbose_name='Corpo da página'),
        ),
    ]
