# Generated by Django 2.1.8 on 2019-06-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("page", "0003_staticpage_teaser_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="staticpage",
            name="show_in_home",
            field=models.BooleanField(
                default=False,
                help_text="Mostrar um link para esta página na página inicial, acima da barra de pesquisa",
                verbose_name="Mostrar na página inicial",
            ),
        ),
    ]
