# Generated by Django 2.1.5 on 2019-03-02 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_auto_20190201_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticpage',
            name='show_in_menu',
            field=models.BooleanField(default=False, verbose_name='Mostrar link no menu'),
        ),
    ]
