# Generated by Django 2.1.5 on 2019-03-02 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_staticpage_show_in_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticpage',
            name='show_in_menu',
            field=models.BooleanField(default=False, verbose_name='Mostrar um link para esta página no menu'),
        ),
    ]
