# Generated by Django 2.1.5 on 2019-03-03 20:05

from django.db import migrations, models
import xram_memory.quill_widget


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0007_auto_20190302_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticpage',
            name='teaser',
            field=models.TextField(blank=True, help_text='Resumo ou chamada', null=True, validators=[xram_memory.quill_widget.no_empty_html], verbose_name='Resumo ou chamada'),
        ),
    ]
