# Generated by Django 2.1.2 on 2019-01-07 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artifact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedNews',
            fields=[
                ('artifact_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='artifact.Artifact')),
            ],
            options={
                'abstract': False,
            },
            bases=('artifact.artifact',),
        ),
    ]
