# Generated by Django 2.1.2 on 2018-12-05 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='Endereço da página da notícia', max_length=255, unique=True, verbose_name='Endereço')),
                ('title', models.CharField(blank=True, help_text='Título', max_length=255, verbose_name='Título')),
                ('downloaded', models.BooleanField(default=False, editable=False, verbose_name='Baixado?')),
                ('authors', models.TextField(blank=True, editable=False, verbose_name='Autores')),
                ('images', models.TextField(blank=True, editable=False, verbose_name='Imagens')),
                ('text', models.TextField(blank=True, editable=False, verbose_name='Texto da notícia')),
                ('top_image', models.FilePathField(blank=True, editable=False, verbose_name='Imagem principal')),
                ('summary', models.TextField(blank=True, editable=False, verbose_name='Resumo do artigo')),
                ('keywords', models.TextField(blank=True, editable=False, verbose_name='palavras-chave')),
            ],
        ),
    ]
