# Generated by Django 2.1.2 on 2018-12-12 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, help_text='Endereço original da notícia', max_length=255, null=True, unique=True, verbose_name='Endereço')),
                ('archived_news_url', models.URLField(blank=True, help_text="Endereço da notícia no <a href='https://archive.org/'>Archive.org</a>", max_length=255, null=True, unique=True, verbose_name='Endereço no Internet Archive')),
                ('title', models.CharField(blank=True, help_text='Título da notícia', max_length=255, verbose_name='Título')),
                ('status', models.PositiveIntegerField(choices=[(100, 'Novo'), (200, 'Em fila para buscar informações básicas'), (201, 'Em fila para capturar a página'), (300, 'Processado com informações básicas'), (301, 'Processado com captura de página'), (302, 'Processado com informações da página arquivada no Internet Archive'), (400, 'Publicado'), (401, 'Publicado, mas escondido'), (500, 'Erro no processamento básico'), (501, 'Erro na captura de página'), (502, 'Erro no processamento automático')], default=100, editable=False, verbose_name='Status')),
                ('authors', models.TextField(blank=True, help_text='Nomes dos autores, separados por vírgula', verbose_name='Autores')),
                ('images', models.TextField(blank=True, editable=False, help_text='Imagens associadas a esta notícia', verbose_name='Imagens')),
                ('text', models.TextField(blank=True, help_text='Texto integral da notícia', verbose_name='Texto da notícia')),
                ('top_image', models.ImageField(blank=True, upload_to='', verbose_name='Imagem principal')),
                ('summary', models.TextField(blank=True, verbose_name='Resumo da notícia')),
                ('page_pdf_file', models.FileField(blank=True, upload_to='saved_news_pages/pdf/', verbose_name='Captura da notícia em PDF')),
                ('force_basic_processing', models.BooleanField(default=True, help_text='Marque se deseja incluir essa notícia para processamento automático.', verbose_name='Buscar automaticamente informações sobre a notícia')),
                ('force_archive_org_processing', models.BooleanField(default=True, help_text="Marque se deseja buscar uma versão arquivada desta notícia no <a href='https://archive.org/'>Archive.org</a>.", verbose_name='Buscar informações no Archive.org')),
                ('force_pdf_capture', models.BooleanField(default=True, help_text='Marque se deseja capturar essa notícia em formato PDF.', verbose_name='Capturar a notícia em formato PDF')),
            ],
            options={
                'verbose_name': 'Archived News',
                'verbose_name_plural': 'Archived News',
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='', editable=False, max_length=60, unique=True)),
                ('name', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Palavra-chave',
                'verbose_name_plural': 'Palavras-chave',
            },
        ),
        migrations.AddField(
            model_name='archivednews',
            name='keywords',
            field=models.ManyToManyField(blank=True, to='archived_news.Keyword', verbose_name='Palavras-chave'),
        ),
    ]
