# Generated by Django 2.1.2 on 2019-01-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('archived_news', '0001_initial'),
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivednews',
            name='keywords',
            field=models.ManyToManyField(blank=True, to='taxonomy.Keyword', verbose_name='Palavras-chave'),
        ),
    ]
