# Generated by Django 2.1.2 on 2018-12-11 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archived_news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivednews',
            name='archived_news_url',
            field=models.URLField(blank=True, help_text="Endereço da notícia no <a href='https://archive.org/'>Archive.org</a>", max_length=255, null=True, unique=True, verbose_name='Endereço no Internet Archive'),
        ),
        migrations.AlterField(
            model_name='archivednews',
            name='url',
            field=models.URLField(blank=True, help_text='Endereço original da notícia', max_length=255, null=True, unique=True, verbose_name='Endereço'),
        ),
    ]
