# Generated by Django 2.1.2 on 2018-12-05 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archived_news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivednews',
            name='downloaded',
        ),
        migrations.AddField(
            model_name='archivednews',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Novo'), (2, 'Em fila para processamento'), (3, 'Processado'), (4, 'Publicado'), (5, 'Escondido')], default=1, editable=False, verbose_name='Baixado?'),
        ),
    ]
