# Generated by Django 2.1.2 on 2018-12-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archived_news', '0002_auto_20181218_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivednews',
            name='published_date',
            field=models.DateTimeField(blank=True, help_text='Data em que a notícia foi publicada', null=True, verbose_name='Data de publicação'),
        ),
    ]
