# Generated by Django 2.1.2 on 2018-12-13 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('archived_news', '0002_auto_20181213_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivednews',
            name='last_modify_user',
        ),
        migrations.AddField(
            model_name='archivednews',
            name='modified_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='last_modifier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='archivednews',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
