# Generated by Django 2.1.2 on 2018-12-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archived_news', '0002_auto_20181211_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivednews',
            name='force_archive_org_processing',
            field=models.BooleanField(default=True, verbose_name='Buscar novamente no Archive.org'),
        ),
        migrations.AlterField(
            model_name='archivednews',
            name='force_basic_processing',
            field=models.BooleanField(default=True, help_text='Marque se deseja incluir essa notícia para processamento automático.\nObserve que isso sobrescreverá qualquer informação que você tiver inserido manualmente.', verbose_name='Pegar novamente informações sobre a página'),
        ),
        migrations.AlterField(
            model_name='archivednews',
            name='force_pdf_capture',
            field=models.BooleanField(default=True, verbose_name='Recapturar a página em formato PDF'),
        ),
    ]
