# Generated by Django 2.1.2 on 2018-12-11 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archived_news', '0003_auto_20181211_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivednews',
            name='force_archive_org_processing',
            field=models.BooleanField(default=True, help_text="Marque se deseja buscar uma versão arquivada desta notícia no <a href='https://archive.org/'>Archive.org</a>.", verbose_name='Buscar informações no Archive.org'),
        ),
        migrations.AlterField(
            model_name='archivednews',
            name='force_basic_processing',
            field=models.BooleanField(default=True, help_text='Marque se deseja incluir essa notícia para processamento automático.\nObserve que isso sobrescreverá qualquer informação que você tiver inserido manualmente.', verbose_name='Pegar automaticamente informações sobre a notícia'),
        ),
        migrations.AlterField(
            model_name='archivednews',
            name='force_pdf_capture',
            field=models.BooleanField(default=True, help_text='Marque se deseja capturar essa notícia em formato PDF.', verbose_name='Capturar a notícia em formato PDF'),
        ),
    ]
