# Generated by Django 2.1.2 on 2018-12-13 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('archived_news', '0003_auto_20181213_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivednews',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='archivednews',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='keyword',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='keyword',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='keyword_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='keyword',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='keyword',
            name='modified_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='keyword_last_modifier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='archivednews',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='archivednews_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='archivednews',
            name='modified_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='archivednews_last_modifier', to=settings.AUTH_USER_MODEL),
        ),
    ]
