# Generated by Django 2.1.2 on 2018-12-06 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archived_news', '0005_auto_20181206_1605'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archivednews',
            options={'verbose_name': 'Archived News', 'verbose_name_plural': 'Archived News'},
        ),
    ]
