# Generated by Django 2.1.2 on 2018-12-06 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archived_news', '0006_auto_20181206_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivednews',
            name='status',
            field=models.PositiveIntegerField(choices=[(100, 'Novo'), (200, 'Em fila para buscar informações básicas'), (201, 'Em fila para capturar a página'), (300, 'Processado com informações básicas'), (301, 'Processado com captura de página'), (400, 'Publicado'), (401, 'Publicado, mas escondido'), (500, 'Erro no processamento básico'), (501, 'Erro na captura de págin')], default=100, editable=False, verbose_name='Status'),
        ),
    ]
