# Generated by Django 2.1.2 on 2018-12-11 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archived_news', '0007_auto_20181211_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivednews',
            name='title',
            field=models.CharField(blank=True, help_text='Título da notícia', max_length=255, verbose_name='Título'),
        ),
    ]
