# Generated by Django 2.1.2 on 2018-12-11 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archived_news', '0009_auto_20181211_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivednews',
            name='manual_insertion',
        ),
    ]
