# Generated by Django 2.1.2 on 2018-12-10 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archived_news', '0010_auto_20181207_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.RemoveField(
            model_name='archivednews',
            name='keywords',
        ),
        migrations.AddField(
            model_name='archivednews',
            name='keywords',
            field=models.ManyToManyField(to='archived_news.Keyword'),
        ),
    ]
