# Generated by Django 2.1.2 on 2018-12-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archived_news', '0011_auto_20181210_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=60, unique=True),
        ),
    ]
