# Generated by Django 2.1.2 on 2018-12-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archived_news', '0013_auto_20181210_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivednews',
            name='keywords',
            field=models.ManyToManyField(blank=True, to='archived_news.Keyword'),
        ),
    ]
