# Generated by Django 2.1.2 on 2018-12-11 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archived_news', '0014_auto_20181210_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivednews',
            name='archived_news_url',
            field=models.URLField(help_text='Endereço da notícia arquivada no Internet Archive', max_length=255, null=True, unique=True, verbose_name='URL no Internet Archive'),
        ),
        migrations.AlterField(
            model_name='archivednews',
            name='page_pdf_file',
            field=models.FileField(blank=True, upload_to='saved_news_pages/pdf', verbose_name='Arquivo da notícia em PDF'),
        ),
        migrations.AlterField(
            model_name='archivednews',
            name='status',
            field=models.PositiveIntegerField(choices=[(100, 'Novo'), (200, 'Em fila para buscar informações básicas'), (201, 'Em fila para capturar a página'), (300, 'Processado com informações básicas'), (301, 'Processado com captura de página'), (302, 'Processado com informações da página arquivada no Internet Archive'), (400, 'Publicado'), (401, 'Publicado, mas escondido'), (500, 'Erro no processamento básico'), (501, 'Erro na captura de página')], default=100, editable=False, verbose_name='Status'),
        ),
    ]
