# Generated by Django 2.1.2 on 2018-12-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archived_news', '0015_auto_20181211_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivednews',
            name='force_archive_org_processing',
            field=models.BooleanField(default=False, verbose_name='Buscar novamente no Archive.org'),
        ),
        migrations.AddField(
            model_name='archivednews',
            name='force_basic_processing',
            field=models.BooleanField(default=False, verbose_name='Pegar novamente informações sobre a página'),
        ),
        migrations.AddField(
            model_name='archivednews',
            name='force_pdf_capture',
            field=models.BooleanField(default=False, verbose_name='Recapturar a página em formato PDF'),
        ),
        migrations.AlterField(
            model_name='archivednews',
            name='url',
            field=models.URLField(help_text='Endereço da página da notícia', max_length=255, null=True, unique=True, verbose_name='Endereço'),
        ),
    ]
