# Generated by Django 2.1.2 on 2018-12-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archived_news', '0016_auto_20181211_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivednews',
            name='page_pdf_file',
            field=models.FileField(blank=True, upload_to='saved_news_pages/pdf/', verbose_name='Arquivo da notícia em PDF'),
        ),
    ]
