# Generated by Django 2.1.2 on 2019-01-07 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artifact', '0001_initial'),
        ('archived_news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedNewsPDFCapture',
            fields=[
                ('artifact_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='artifact.Artifact')),
                ('size', models.PositiveIntegerField(default=0, editable=False)),
                ('mime_type', models.CharField(blank=True, editable=False, max_length=255)),
                ('url_of_capture', models.URLField(blank=True, editable=False, help_text='Endereço original da notícia que gerou essa captura', max_length=255, null=True, verbose_name='Endereço')),
                ('pdf_file', models.FileField(blank=True, upload_to='saved_news_pages/pdf/', verbose_name='Captura da notícia em PDF')),
                ('archived_news', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pdf_captures', to='archived_news.ArchivedNews')),
            ],
            options={
                'abstract': False,
            },
            bases=('artifact.artifact',),
        ),
        migrations.CreateModel(
            name='PDFFile',
            fields=[
                ('artifact_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='artifact.Artifact')),
                ('size', models.PositiveIntegerField(default=0, editable=False)),
                ('mime_type', models.CharField(blank=True, editable=False, max_length=255)),
                ('pdf_file', models.FileField(blank=True, upload_to='saved_news_pages/pdf/', verbose_name='Arquivo em PDF')),
            ],
            options={
                'abstract': False,
            },
            bases=('artifact.artifact',),
        ),
    ]
