# Generated by Django 2.1.2 on 2019-01-07 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artifact', '0001_initial'),
        ('archived_news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedNewsPDFCapture',
            fields=[
                ('artifact_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='artifact.Artifact')),
                ('filename', models.CharField(max_length=255)),
                ('archived_news', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parent_archived_news', to='archived_news.ArchivedNews')),
            ],
            options={
                'abstract': False,
            },
            bases=('artifact.artifact',),
        ),
        migrations.CreateModel(
            name='PDFFile',
            fields=[
                ('artifact_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='artifact.Artifact')),
                ('filename', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('artifact.artifact',),
        ),
    ]
