# Generated by Django 2.1.2 on 2018-12-18 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('archived_news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedNewsPDFCapture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('size', models.PositiveIntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, editable=False, max_length=255)),
                ('url_of_capture', models.URLField(blank=True, help_text='Endereço original da notícia que gerou essa captura', max_length=255, null=True, unique=True, verbose_name='Endereço')),
                ('pdf_file', models.FileField(blank=True, upload_to='saved_news_pages/pdf/', verbose_name='Captura da notícia em PDF')),
                ('archived_news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archived_news.ArchivedNews')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
