# Generated by Django 2.1.2 on 2018-12-18 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_auto_20181218_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivednewspdfcapture',
            name='archived_news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pdf_captures', to='archived_news.ArchivedNews'),
        ),
    ]
