# Generated by Django 2.1.2 on 2018-12-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_auto_20181218_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivednewspdfcapture',
            name='size',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
