# Generated by Django 2.1.5 on 2019-01-26 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='language',
            field=models.CharField(blank=True, default='pt', max_length=2, null=True),
        ),
    ]
