# Generated by Django 2.1.2 on 2019-01-18 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taxonomy', '0001_initial'),
        ('artifact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='news_creator', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='news',
            name='keywords',
            field=models.ManyToManyField(blank=True, to='taxonomy.Keyword', verbose_name='Palavras-chave'),
        ),
        migrations.AddField(
            model_name='news',
            name='modified_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='news_last_modifier', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='news',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='taxonomy.Subject', verbose_name='Assuntos'),
        ),
        migrations.AddField(
            model_name='document',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_creator', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='document',
            name='keywords',
            field=models.ManyToManyField(blank=True, to='taxonomy.Keyword', verbose_name='Palavras-chave'),
        ),
        migrations.AddField(
            model_name='document',
            name='modified_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_last_modifier', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='document',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='taxonomy.Subject', verbose_name='Assuntos'),
        ),
        migrations.CreateModel(
            name='PDFDocument',
            fields=[
            ],
            options={
                'verbose_name': 'Documento PDF',
                'verbose_name_plural': 'Documentos PDF',
                'proxy': True,
                'indexes': [],
            },
            bases=('artifact.document',),
        ),
        migrations.AddField(
            model_name='newspdfcapture',
            name='pdf_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artifact.PDFDocument'),
        ),
    ]
