# Generated by Django 2.1.2 on 2019-01-20 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifact', '0002_auto_20190120_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='archived_news_url',
            field=models.URLField(blank=True, help_text="Endereço da notícia no <a href='https://archive.org/'>Archive.org</a>",
                                  max_length=255, null=True, verbose_name='Endereço no Internet Archive'),
        ),
    ]
