# Generated by Django 2.1.5 on 2019-01-26 22:45

from django.db import migrations
import easy_thumbnails.fields
import xram_memory.artifact.models.documents
import xram_memory.utils


class Migration(migrations.Migration):

    dependencies = [
        ('artifact', '0002_news_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=easy_thumbnails.fields.ThumbnailerField(upload_to=xram_memory.artifact.models.documents.get_file_path, validators=[xram_memory.utils.FileValidator(content_types=('image/jpeg', 'image/png', 'image/gif', 'image/webp', 'application/pdf'))], verbose_name='Arquivo'),
        ),
    ]
