# Generated by Django 2.1.7 on 2019-03-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifact', '0002_auto_20190320_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, help_text='Parte do endereço pelo qual este artefato poderá ser acessado', verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='newspaper',
            name='slug',
            field=models.SlugField(blank=True, help_text='Parte do endereço pelo qual este artefato poderá ser acessado', verbose_name='Endereço'),
        ),
    ]
