# Generated by Django 2.1.7 on 2019-03-19 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artifact', '0002_auto_20190319_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsimagecapture',
            name='image_document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='filer.File', verbose_name='Documento de imagem'),
        ),
        migrations.AlterField(
            model_name='newspdfcapture',
            name='pdf_document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='filer.File', verbose_name='Documento PDF'),
        ),
    ]
