# Generated by Django 2.1.2 on 2019-01-20 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artifact', '0003_auto_20190120_1550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='aditional_info',
            new_name='additional_info',
        ),
    ]
