# Generated by Django 2.1.5 on 2019-02-04 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifact', '0003_auto_20190126_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='document', to='taxonomy.Keyword', verbose_name='Palavras-chave'),
        ),
        migrations.AlterField(
            model_name='document',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='document', to='taxonomy.Subject', verbose_name='Assuntos'),
        ),
        migrations.AlterField(
            model_name='news',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='news', to='taxonomy.Keyword', verbose_name='Palavras-chave'),
        ),
        migrations.AlterField(
            model_name='news',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='news', to='taxonomy.Subject', verbose_name='Assuntos'),
        ),
    ]
