# Generated by Django 2.1.7 on 2019-03-23 14:53

from django.db import migrations
import django.db.models.deletion
import filer.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ('artifact', '0003_auto_20190323_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspdfcapture',
            name='pdf_document',
            field=filer.fields.file.FilerFileField(on_delete=django.db.models.deletion.CASCADE, to='filer.File', verbose_name='Documento PDF'),
        ),
    ]
