# Generated by Django 2.1.7 on 2019-04-08 13:50

from django.db import migrations
from django.conf import settings

DEFAULT_FOLDERS = settings.DEFAULT_FOLDERS


def create_default_folders(apps, schema_editor):
    Folder = apps.get_model('filer', 'Folder')

    for i, folder in enumerate(DEFAULT_FOLDERS):
        Folder.objects.get_or_create(**folder)


def reverse_create_default_folders(apps, schema_editor):
    Folder = apps.get_model('filer', 'Folder')

    for i, folder in enumerate(DEFAULT_FOLDERS):
        try:
            Folder.objects.filter(**folder).delete()
        except Folder.DoesNotExist:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0010_auto_20180414_2058'),
        ('artifact', '0005_auto_20190323_1158')
    ]

    operations = [
        migrations.RunPython(create_default_folders,
                             reverse_create_default_folders)
    ]
