# Generated by Django 2.1.2 on 2019-01-21 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifact', '0006_auto_20190120_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file_size',
            field=models.CharField(default='0', editable=False, help_text='Tamanho do arquivo em bytes', max_length=100, verbose_name='Tamanho'),
        ),
        migrations.AlterField(
            model_name='document',
            name='mime_type',
            field=models.CharField(blank=True, editable=False, help_text='Tipo do arquivo', max_length=255, verbose_name='Tipo'),
        ),
    ]
