# Generated by Django 2.1.5 on 2019-02-17 20:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields
import xram_memory.utils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artifact', '0006_auto_20190217_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newspaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('published', models.BooleanField(default=True, verbose_name='Publicado?')),
                ('featured', models.BooleanField(default=True, verbose_name='Em destaque na página inicial?')),
                ('title', models.CharField(blank=True, help_text='Título', max_length=255, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, verbose_name='Slug')),
                ('url', models.URLField(help_text='Endereço do site', max_length=255, unique=True, validators=[django.core.validators.URLValidator], verbose_name='Endereço')),
                ('description', models.TextField(blank=True, help_text='A descrição desse veículo/site', verbose_name='Descrição')),
                ('logo', easy_thumbnails.fields.ThumbnailerField(blank=True, upload_to='news_sources_logos', validators=[xram_memory.utils.FileValidator(content_types=('image/jpeg', 'image/png', 'image/gif', 'image/webp'))], verbose_name='Logotipo')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='newspaper_creator', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='newspaper_last_modifier', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='newssource',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='newssource',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='news',
            name='news_source',
        ),
        migrations.DeleteModel(
            name='NewsSource',
        ),
        migrations.AddField(
            model_name='news',
            name='newspaper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artifact.Newspaper'),
        ),
    ]
