# Generated by Django 2.1.8 on 2019-04-17 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artifact', '0006_auto_20190416_1924'),
        ('artifact', '0006_auto_20190408_1050'),
    ]

    operations = [
    ]
