# Generated by Django 2.1.5 on 2019-02-23 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artifact', '0008_auto_20190217_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsimagecapture',
            name='news',
        ),
        migrations.AddField(
            model_name='news',
            name='image_capture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to='artifact.NewsImageCapture'),
        ),
    ]
