# Generated by Django 2.1.5 on 2019-02-24 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artifact', '0009_auto_20190223_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='image_capture',
        ),
        migrations.AddField(
            model_name='newsimagecapture',
            name='news',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_capture', to='artifact.News', verbose_name='Notícia'),
        ),
    ]
