# Generated by Django 2.1.5 on 2019-02-24 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifact', '0010_auto_20190223_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsimagecapture',
            name='original_url',
            field=models.CharField(max_length=255, verbose_name='Endereço original da imagem'),
        ),
    ]
