# Generated by Django 2.1.14 on 2019-12-06 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artifact', '0011_auto_20190529_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentPage',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='artifact.Document')),
                ('page_index', models.PositiveIntegerField(verbose_name='Página')),
                ('parent_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_pages', to='artifact.Document')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('artifact.document',),
        ),
    ]
