# Generated by Django 2.1.5 on 2019-02-25 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifact', '0011_auto_20190223_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='body',
            field=models.TextField(blank=True, help_text='Texto integral da notícia', null=True, verbose_name='Texto da notícia'),
        ),
    ]
