# Generated by Django 2.1.2 on 2018-12-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(default='', editable=False, max_length=60, unique=True)),
                ('name', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Palavra-chave',
                'verbose_name_plural': 'Palavras-chave',
            },
        ),
    ]
