# Generated by Django 2.1.2 on 2019-01-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0002_auto_20190120_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=60, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=60, unique=True, verbose_name='Slug'),
        ),
    ]
