# Generated by Django 2.1.10 on 2019-07-15 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filer', '0010_auto_20180414_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured', models.BooleanField(verbose_name='Em destaque na página de álbums')),
                ('folder', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='album', to='filer.Folder')),
            ],
        ),
    ]
