# Generated by Django 2.1.10 on 2019-07-15 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("albums", "0003_auto_20190715_0117"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="album",
            name="id",
        ),
        migrations.AlterField(
            model_name="album",
            name="folder",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="album",
                serialize=False,
                to="filer.Folder",
            ),
        ),
    ]
